@extends('layouts.app')
@section('content')
<div class="card p-3"><div class="d-flex justify-content-between align-items-center mb-2"><h5 class="mb-0">{{ __('gmao.maintenance.tasks') }}</h5><div class="d-flex align-items-center gap-2"><a class="action-icon" href="{{ route('maintenance.tasks.create') }}"><i class="bi bi-plus-square"></i><span>{{ __('gmao.common.add') }}</span></a><form method="GET" class="d-flex gap-1"><select class="form-select form-select-sm" name="sector"><option value="">{{ __('gmao.common.all_sectors') }}</option>@foreach($sectors as $sector)<option value="{{ $sector }}" @selected($selectedSector === $sector)>{{ __('gmao.enum.sector.'.$sector) }}</option>@endforeach</select><button class="btn btn-sm btn-outline-secondary">{{ __('gmao.common.search') }}</button></form></div></div>
<div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>#</th><th>{{ __('gmao.common.title') }}</th><th>{{ __('gmao.common.sector') }}</th><th>{{ __('gmao.common.type') }}</th><th>{{ __('gmao.common.status') }}</th><th>{{ __('gmao.common.date') }}</th><th>{{ __('gmao.common.actions') }}</th></tr></thead><tbody>
@forelse($tasks as $t)<tr><td>{{ $t->id }}</td><td>{{ $t->title }}</td><td>{{ $t->sector ? __('gmao.enum.sector.'.$t->sector) : '-' }}</td><td>{{ __('gmao.enum.type.'.$t->type) }}</td><td>{{ __('gmao.enum.status.'.$t->status) }}</td><td>{{ $t->scheduled_for }}</td><td><a class="btn btn-sm btn-outline-success" href="{{ route('assets.reports.create', ['context_type' => 'maintenance_task', 'context_id' => $t->id]) }}"><i class="bi bi-file-earmark-plus"></i></a> <a class="btn btn-sm btn-outline-info" href="{{ route('assets.reports', ['context_type' => 'maintenance_task', 'context_id' => $t->id]) }}"><i class="bi bi-files"></i></a>
@can('update', $t)<details><summary class="btn btn-sm btn-outline-primary">{{ __('gmao.common.edit') }}</summary><form method="POST" action="{{ route('maintenance.tasks.update', $t) }}" class="vstack gap-1 mt-1">@csrf @method('PATCH')
<input class="form-control form-control-sm" name="title" value="{{ $t->title }}" required><select class="form-select form-select-sm" name="sector"><option value="">{{ __('gmao.common.sector') }}</option>@foreach($sectors as $sector)<option value="{{ $sector }}" @selected($t->sector === $sector)>{{ __('gmao.enum.sector.'.$sector) }}</option>@endforeach</select><select class="form-select form-select-sm" name="type">@foreach(['corrective','preventive','predictive'] as $type)<option value="{{ $type }}" @selected($t->type === $type)>{{ __('gmao.enum.type.'.$type) }}</option>@endforeach</select><select class="form-select form-select-sm" name="status">@foreach(['pending','in_progress','completed','stopped'] as $status)<option value="{{ $status }}" @selected($t->status === $status)>{{ __('gmao.enum.status.'.$status) }}</option>@endforeach</select><select class="form-select form-select-sm" name="maintenance_request_id"><option value="">{{ __('gmao.maintenance.link_request') }}</option>@foreach($requests as $r)<option value="{{ $r->id }}" @selected($t->maintenance_request_id === $r->id)>#{{ $r->id }}</option>@endforeach</select><select class="form-select form-select-sm" name="technician_id"><option value="">{{ __('gmao.maintenance.tech_responsible') }}</option>@foreach($technicians as $tech)<option value="{{ $tech->id }}" @selected($t->technician_id === $tech->id)>{{ $tech->name }}</option>@endforeach</select><input class="form-control form-control-sm" type="date" name="scheduled_for" value="{{ $t->scheduled_for }}"><input class="form-control form-control-sm" type="number" step="0.25" name="estimated_hours" value="{{ $t->estimated_hours }}"><input class="form-control form-control-sm" type="number" step="0.25" name="actual_hours" value="{{ $t->actual_hours }}" placeholder="{{ __('gmao.maintenance.actual_hours') }}"><textarea class="form-control form-control-sm" name="notes">{{ $t->notes }}</textarea><button class="btn btn-sm btn-primary">{{ __('gmao.common.update') }}</button></form></details>@endcan
@can('delete', $t)<form method="POST" action="{{ route('maintenance.tasks.destroy', $t) }}" class="mt-1" onsubmit="return confirm('{{ __('gmao.common.confirm_delete') }}')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">{{ __('gmao.common.delete') }}</button></form>@endcan
</td></tr>
@empty <tr><td colspan="7" class="text-center">{{ __('gmao.common.none') }}</td></tr> @endforelse
</tbody></table></div>{{ $tasks->links() }}</div>
@endsection
